### ISSUE TITLE
Units of Energies SSE, SPD in UMAT

### ISSUE THREAD

**Issue by kengwit** [jpsferreira/UMAT-ABAQUS#2]
This is nice work. I have a question: do you know why the variable SSE in UMAT is defined (in the Abaqus documentation) to be "SPECIFIC elastic strain energy"? Your UMAT code ([umat_general.for](https://github.com/jpsferreira/UMAT-ABAQUS/blob/master/umat_general.for)) suggests that SSE has units of energy per unit (reference) volume, but "specific" means per unit mass. I am guessing SPD would have the same units as SSE? Do you know whether the Abaqus documentation is incorrect?

**Comment by jpsferreira** [comment]
Hi @kengwit , that's a great question! 
I usually run problems where the material has a mass density of 1 (unit value) and is homogenous throughout the whole volume. I guess in such conditions the term "specific" works either per unit mass or per unit volume.

**Comment by kengwit** [comment]
Thank you for your explanation, which makes sense.
